version: "3"
services:
  # ローカルテスト用
  lambda:
    build:
      context: .
    volumes:
      - ./app:/app
      - ./entrypoint.sh:/scripts/entrypoint.sh
    working_dir: /app
    tty: true
    ports:
      - 9000:8080
    entrypoint: /scripts/entrypoint.sh
    command: app.lambda_handler
    environment:
      # /modulesはawslambdaric用
      - PYTHONPATH=/modules:/app/modules
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
  # pip install用
  installer:
    image: python:3.9-buster
    volumes:
      - ./app:/src
    working_dir: /src
    command: bash -c "pip install --upgrade pip && pip install --target /src/modules --upgrade -r /src/requirements.txt"
  terraform:
    image: alpine/terragrunt
    volumes:
      - .:/app
    working_dir: /app
